# electron-builder configuration in TOML
# https://www.electron.build/configuration/configuration

# Auto Update: https://www.electron.build/auto-update

productName = "testron"
appId = "com.electron.test"
asar = true
compression = "normal"
files = ["dist/**/*"]
extraResources = ["assets/**/*"]

[publish]
provider = "github"
token = "${env.GH_TOKEN}"
releaseType = "release"

[directories]
buildResources = "assets/"
output = "build/"

# Windows Store App

[appx]
displayName = "testron"
identityName = "ttt"
publisherDisplayName = "lightyen"

# Windows NSIS

[nsis]
shortcutName = "testron"
oneClick = true
createDesktopShortcut = true
createStartMenuShortcut = true
menuCategory = true
language = 1033
runAfterFinish = false

# For Windows

[win]
target = ["nsis"]
# certificateFile = "certificate.pfx"
icon = "./assets/appicons/256x256.png"

# For Linux

[linux]
target = ["AppImage"]
executableName= "testron"
icon = "assets/appicons/"
synopsis = "A electron example"
vendor = "lightyen"
maintainer = "lightyen <lightyen0123@gmail.com>"
description = "test electron"
category = "Network"

# For MacOS (I haven't try it yet!!!)

[mac]
target = ["default"]
category = "public.app-category.social-networking"
